name: Buddy
options:
  bundleIdPrefix: com.ironx
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true
  generateEmptyDirectories: true
  
settings:
  base:
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM: ""
    DEVELOPMENT_LANGUAGE: fr
    
targets:
  Buddy:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: Buddy
        createIntermediateGroups: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ironx.buddy
        PRODUCT_NAME: Buddy
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: Buddy/App/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
    info:
      path: Buddy/App/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: LaunchScreenBackground
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
