name: Buddy
options:
  bundleIdPrefix: com.ironx
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true
  
settings:
  base:
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM: ""
    
targets:
  Buddy:
    type: application
    platform: iOS
    sources:
      - Buddy
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ironx.buddy
        PRODUCT_NAME: Buddy
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
